development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: exchange_rates_production

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: exchange_rates_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: exchange_rates_production
