development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: exchange_rates_production

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_PROVIDER"] %>
  channel_prefix: exchange_rates_production
