defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *defaults
  database: exchange_rates_dev

test:
  <<: *defaults
  database: exchange_rates_test
  username: postgres
  password:

production:
  <<: *defaults
  database: exchange_rates_prod
