defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: root
  password: 13666
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *defaults
  database: exchange_rates_dev

test:
  <<: *defaults
  database: exchange_rates_test

production:
  <<: *defaults
  database: exchange_rates_prod